CREATE TABLE IF NOT EXISTS TS AS FROM read_csv('./sample_data/src/TIMESERIES_IDS_COSMOS.csv', AUTO_DETECT=true);
CREATE TABLE IF NOT EXISTS MEASURE AS FROM read_csv('./sample_data/src/MEASURES.csv', AUTO_DETECT=true);
CREATE TABLE IF NOT EXISTS SI AS FROM read_csv('./sample_data/src/SITE_INSTRUMENTATION.csv', AUTO_DETECT=true);
CREATE TABLE IF NOT EXISTS CG AS FROM read_csv('./sample_data/src/COLUMN_GROUPS_COSMOS.csv', AUTO_DETECT=true);
CREATE TABLE IF NOT EXISTS CG_SPLIT AS
    SELECT
        COLUMN_GROUP, str_split(COLUMN_NAMES, ';').UNNEST() AS COLUMN_NAME
    FROM
	    CG ;

COPY (
    SELECT DISTINCT MEASURE.PARAMETER_ID, SI.INSTRUMENT_ID
    FROM TS 
        JOIN MEASURE ON TS.MEASURE_ID == MEASURE.ID
        JOIN CG_SPLIT ON TS.COLUMN_NAME == CG_SPLIT.COLUMN_NAME
        JOIN SI ON CG_SPLIT.COLUMN_GROUP == SI.COLUMN_GROUP AND TS.SITE_ID == SI.SITE_ID
)TO './build/instrumentation_parameters.csv' (HEADER, DELIMITER ',') ;