create table if not exists SITE_INSTRUMENTATION as from read_csv('./sample_data/src/SITE_INSTRUMENTATION.csv', AUTO_DETECT=true) ;
create table if not exists SENSOR_SLOT_IDS as from read_csv('./sample_data/src/SENSOR_SLOT_IDS.csv', AUTO_DETECT=true) ;
create table if not exists CALIB_FACTORS as select *, strptime(START_DATETIME, '%d-%m-%Y %H:%M') as START_TIMESTAMP,
    strptime(END_DATETIME, '%d-%m-%Y %H:%M') as END_TIMESTAMP from read_csv('./sample_data/src/calib_factors_nr01_anem.csv', AUTO_DETECT=true) ;
create table if not exists TS as from read_csv('./sample_data/src/TIMESERIES_IDS_COSMOS.csv', AUTO_DETECT=true) ;
create table if not exists MEASURES as from read_csv('./sample_data/src/MEASURES.csv', AUTO_DETECT=true) ;

COPY(
    SELECT SENSOR_SLOT_IDS.INSTRUMENT_ID AS INSTRUMENT_ID,
        INSTANCE,
        SERIAL_NUMBER,
        VARIABLE,
        TS.TIMESERIES_ID,
        CALIB_FACTORS.DESCRIPTION AS DECSRIPTION,
        strftime(START_TIMESTAMP, '%Y-%m-%dT%H:%M:%SZ') as START_TIMESTAMP,
        strftime(END_TIMESTAMP, '%Y-%m-%dT%H:%M:%SZ') as END_TIMESTAMP,
        CORRECTION_ID,
        CORRECTION_FACTOR
    FROM TS
    LEFT JOIN SENSOR_SLOT_IDS ON TS.SENSOR_SLOT_ID=SENSOR_SLOT_IDS.SENSOR_SLOT_ID
    INNER JOIN MEASURES ON TS.MEASURE_ID=MEASURES.ID AND TS.PROCESS_LEVEL='RAW'
    INNER JOIN CALIB_FACTORS ON CALIB_FACTORS.SITE_ID==TS.SITE_ID AND MEASURES.PARAMETER_ID=CALIB_FACTORS.VARIABLE
    INNER JOIN SITE_INSTRUMENTATION ON SITE_INSTRUMENTATION.SITE_ID=TS.SITE_ID AND
        SITE_INSTRUMENTATION.SENSOR_SLOT_ID=TS.SENSOR_SLOT_ID AND
        SITE_INSTRUMENTATION.START_DATETIME <= CALIB_FACTORS.END_TIMESTAMP AND
        SITE_INSTRUMENTATION.END_DATETIME >= CALIB_FACTORS.END_TIMESTAMP
) TO './build/sensor_calibrations.csv' (HEADER, DELIMITER ',') ;