CREATE TABLE IF NOT EXISTS SI AS FROM read_csv('./sample_data/src/SITE_INSTRUMENTATION.csv', AUTO_DETECT=true) ;
CREATE TABLE IF NOT EXISTS TS AS FROM read_csv('./sample_data/src/TIMESERIES_IDS_COSMOS.csv', AUTO_DETECT=true) ;
CREATE TABLE IF NOT EXISTS MEASURE AS FROM read_csv('./sample_data/src/MEASURES.csv', AUTO_DETECT=true) ;

COPY (
    SELECT SI.*, MEASURE.PARAMETER_ID
    FROM
    SI LEFT JOIN TS on SI.COLUMN_NAME = TS.COLUMN_NAME AND SI.SITE_ID = TS.SITE_ID
       LEFT JOIN MEASURE ON TS.MEASURE_ID=MEASURE.ID
) TO './build/sensor_deployments.csv' (HEADER, DELIMITER ',') ;
