globals:
  $baseURI: http://fdri.ceh.ac.uk/
  $datasetID: cosmos

imports:
  - namespaces.yaml
  - extensions.py

one_offs:
  - name: PriorityAnnotationProperty
    properties:
      "@id": "<http://fdri.ceh.ac.uk/ref/common/cop/data-processing-configuration-priority>"
      "@type": "<fdri:Variable>"
      "<iop:hasObjectOfInterest>": <fdri:DataProcessingConfiguration>
      "<iop:hasProperty>": "<http://fdri.ceh.ac.uk/ref/common/parameter/priority>"

resources:
  - name: DataProcessingConfiguration
    properties:
      "@id": "<http://fdri.ceh.ac.uk/id/data-processing-configuration/cosmos-infill-{FACILITY_ID|slug}-{VARIABLE_ID|slug}>"
      "@type": "<fdri:InternalDataProcessingConfiguration>"
      "<dct:type>": "<http://fdri.ceh.ac.uk/ref/common/data-processing-configuration-type/infill-configuration>"
      "<fdri:appliesToFacility>": "<http://fdri.ceh.ac.uk/id/site/cosmos-{FACILITY_ID|slug}>"
      "<fdri:appliesToTimeSeries>": <http://fdri.ceh.ac.uk/id/dataset/cosmos-{FACILITY_ID|slug}-{VARIABLE_ID}>

  - name: PriorityAnnotation
    properties:
      "@id": "<http://fdri.ceh.ac.uk/id/annotation/cosmos-infill-{FACILITY_ID|slug}-{VARIABLE_ID|slug}-{PRIORITY|slug}>"
      "^<fdri:hasAnnotation>": <::DataProcessingConfiguration>
      "<fdri:property>": "<::PriorityAnnotationProperty>"
      "<fdri:hasValue>":
        - name: PriorityAnnotationValue
          properties:
            "@id": "<_>"
            "@type": "<schema:PropertyValue>"
            "<schema:value>": "{PRIORITY}^^<xsd:integer>"

  - name: AltDataProcessingConfigurationItem
    properties:
      "@id": "<http://fdri.ceh.ac.uk/id/configuration-item/cosmos-alt_data-configuration-{FACILITY_ID|slug}-{VARIABLE_ID|slug}-{PRIORITY|slug}-{START_DATETIME|slug}-{ALT_FACILITY_ID}-{ALT_VARIABLE_ID}>"
      "@type": <fdri:ConfigurationItem>
      "<fdri:method>": <http://fdri.ceh.ac.uk/ref/common/method/infill-{METHOD|slug}>
      "<fdri:argument>":
        - name: CorrectionFactor
          requires:
            CORRECTION_FACTOR:
          properties:
            "@id": "<_>"
            "@type": <fdri:Argument>
            "<fdri:parameter>": <http://fdri.ceh.ac.uk/ref/common/configuration-parameter/correction_factor>
            "<fdri:hasValue>":
              name: CorrectionFactorValue
              properties:
                "@id": "<_>"
                "@type": <schema:PropertyValue>
                "<schema:value>": "{CORRECTION_FACTOR}^^<xsd:decimal>"

  - name: CurrentConfigurationItem
    properties:
      "@id": "<http://fdri.ceh.ac.uk/id/configuration-item/cosmos-alt_data-{FACILITY_ID|slug}-{VARIABLE_ID|slug}-{PRIORITY|slug}-{START_DATETIME|slug}>"
      "@type": <fdri:ConfigurationItem>
      "^<fdri:hasCurrentConfiguration>": <::DataProcessingConfiguration>
      "<fdri:method>": "<http://fdri.ceh.ac.uk/ref/common/method/alt_data>"
      "<fdri:observationInterval>":
        - name: ClosedConfigurationInterval
          requires:
            END_DATETIME:
          properties:
            "@id": "<_>"
            "@type": <dct:PeriodOfTime>
            "<dcat:startDate>": "{START_DATETIME}^^<xsd:dateTime>"
            "<dcat:endDate>": "{END_DATETIME}^^<xsd:dateTime>"
        - name: OpenConfigurationInterval
          requires:
            END_DATETIME: ""
          properties:
            "@id": "<_>"
            "@type": <dct:PeriodOfTime>
            "<dcat:startDate>": "{START_DATETIME}^^<xsd:dateTime>"
      "<fdri:argument>":
        - name: AltData
          properties:
            "@id": "<_>"
            "@type": "<fdri:Argument>"
            "<fdri:parameter>": <http://fdri.ceh.ac.uk/ref/common/parameter/alt_data-timeseries>
            "<fdri:hasValue>":
              - name: AltDataValue
                properties:
                  "@id": "<_>"
                  "@type": <schema:PropertyValue>
                  "<schema:valueReference>": <http://fdri.ceh.ac.uk/id/dataset/cosmos-{ALT_FACILITY_ID|slug}-{ALT_VARIABLE_ID|slug}>
        - name: AltDataConfig
          properties:
            "@id": "<_>"
            "@type": "<fdri:Argument>"
            "<fdri:parameter>": <http://fdri.ceh.ac.uk/ref/common/parameter/alt_data-configuration>
            "<fdri:hasValue>":
                name: AltDataConfigValue
                properties:
                  "@id": <_>
                  "@type": <schema:PropertyValue>
                  "<schema:valueReference>": "<::AltDataProcessingConfigurationItem>"
