globals:
  $baseURI: http://fdri.ceh.ac.uk/
  $datasetID: cosmos

imports:
  - namespaces.yaml
  - extensions.py
  - concept_schemes.yaml

one_offs:
  - name: CorrectionConfiguration
    properties:
      "@id": "<http://fdri.ceh.ac.uk/ref/common/configuration-type/correction-configuration>"
      "@type": "<fdri:DataProcessingConfigurationType>"
      "<skos:prefLabel>": "FDRI Correction Configuration@en"
      "<rdfs:label>": "FDRI Correction Configuration@en"
      "<skos:inScheme>": "<::ConfigurationTypeScheme>"
      "^<skos:hasTopConcept>": "<::ConfigurationTypeScheme>"

embedded:
  - name: ConfigurationArgument
    properties:
      "@id": "<http://fdri.ceh.ac.uk/id/argument/{|hash(PARAM_ID, PARAM_VALUE)|slug}>"
      "@type": <fdri:ConfigurationArgument>
      "<fdri:parameter>": "<http://fdri.ceh.ac.uk/ref/common/parameter/{PARAM_ID|slug}>"
      "<fdri:hasValue>":
        - name: TSParamValue
          requires:
            PARAM_ID:
             - DEP_TS
          properties:
            "@id": <http://fdri.ceh.ac.uk/id/argument/{|hash(PARAM_ID, PARAM_VALUE)|slug}#value>
            "@type": <schema:PropertyValue>
            "<schema:valueReference>": "<http://fdri.ceh.ac.uk/id/dataset/{PARAM_VALUE|slug}>"
        - name: StringParamValue
          requires:
            PARAM_ID:
             - SITE_ATTRIBUTE
          properties:
            "@id": <http://fdri.ceh.ac.uk/id/argument/{|hash(PARAM_ID, PARAM_VALUE)|slug}#value>
            "<schema:value>": "{PARAM_VALUE}^^<xsd:string>"
        - name: DecimalParamValue
          unless:
            PARAM_ID:
              - DEP_TS
              - SITE_ATTRIBUTE
          properties:
            "@id": <http://fdri.ceh.ac.uk/id/argument/{|hash(PARAM_ID, PARAM_VALUE)|slug}#value>
            "<schema:value>": "{PARAM_VALUE|asDecimal}^^<xsd:decimal>"

resources:
  - name: Configuration
    properties:
      "@id": "<http://fdri.ceh.ac.uk/id/data-processing-configuration/{|hash(CORRECT_TS, METHOD_ID, OBS_START_DATETIME)|slug}>"
      "@type": <fdri:InternalDataProcessingConfiguration>
      "<dct:type>": <http://fdri.ceh.ac.uk/ref/common/configuration-type/correction-configuration>
      "<fdri:appliesToTimeSeries>": "<http://fdri.ceh.ac.uk/id/dataset/{CORRECT_TS|slug}>"
      "<dct:title>": "Correction Configuration for {CORRECT_TS}@en"

  - name: ConfigurationItem
    properties:
      "@id": "<http://fdri.ceh.ac.uk/id/configuration-item/{|hash(CORRECT_TS, METHOD_ID, OBS_START_DATETIME, USE_START_DATETIME)|slug}>"
      "@type": <fdri:ConfigurationItem>
      "<rdfs:label>": "{DESCRIPTION}: {CORRECT_TS}@en"
      "^<fdri:hasCurrentConfiguration>": "<::Configuration>"
      "<fdri:method>": "<http://fdri.ceh.ac.uk/ref/common/method/{METHOD_ID|slug}>"
      "<fdri:observationInterval>":
        - name: ClosedObservationInterval
          requires:
            OBS_END_DATETIME:
          properties:
            "@id": "<http://fdri.ceh.ac.uk/id/observation-interval/{OBS_START_DATETIME|slug}-{OBS_END_DATETIME|slug}>"
            "@type": <dct:PeriodOfTime>
            "<dcat:startDate>": "{OBS_START_DATETIME}^^<xsd:dateTime>"
            "<dcat:endDate>": "{OBS_END_DATETIME}^^<xsd:dateTime>"
        - name: OpenObservationInterval
          unless:
            OBS_END_DATETIME:
          properties:
            "@id": "<http://fdri.ceh.ac.uk/id/observation-interval/{OBS_START_DATETIME|slug}>"
            "@type": <dct:PeriodOfTime>
            "<dcat:startDate>": "{OBS_START_DATETIME}^^<xsd:dateTime>"
      "<fdri:argument>": "{parameters|map_to('ConfigurationArgument')}"