globals:
  $baseURI: http://fdri.ceh.ac.uk/
  $datasetID: cosmos

imports:
  - namespaces.yaml
  - extensions.py

one_offs:

resources:
  - name: MaskConfiguration
    properties:
      "@id": "<http://fdri.ceh.ac.uk/id/data-processing-configuration/{SITE_ID|slug}-{FEATURE_ID|slug}-mask-{RESOLUTION|slug}-configuration>"
      "@type": "<fdri:InternalDataProcessingConfiguration>"
      "<dct:type>": <http://fdri.ceh.ac.uk/ref/common/data-processing-configuration-type/phenocam-mask>
      "<fdri:appliesToFacility>": <http://fdri.ceh.ac.uk/id/site/{SITE_ID|slug}>
      "<fdri:appliesToTimeSeries>":
        - <http://fdri.ceh.ac.uk/ref/cosmos/time-series/image_red_{FEATURE_ID|slug}>
        - <http://fdri.ceh.ac.uk/ref/cosmos/time-series/image_green_{FEATURE_ID|slug}>
        - <http://fdri.ceh.ac.uk/ref/cosmos/time-series/image_blue_{FEATURE_ID|slug}>
        - <http://fdri.ceh.ac.uk/ref/cosmos/time-series/image_red_{FEATURE_ID|slug}_daily>
        - <http://fdri.ceh.ac.uk/ref/cosmos/time-series/image_green_{FEATURE_ID|slug}_daily>
        - <http://fdri.ceh.ac.uk/ref/cosmos/time-series/image_blue_{FEATURE_ID|slug}_daily>
  - name: ConfigurationItem
    properties:
      "@id": "<http://fdri.ceh.ac.uk/id/configuration-item/{SITE_ID|slug}-{FEATURE_ID|slug}-{RESOLUTION|slug}-{SEQ|slug}>"
      "@type": <fdri:ConfigurationItem>
      "<fdri:method>": <http://fdri.ceh.ac.uk/ref/common/method/image_mask>
      "<fdri:argument>":
        - name: MaskFilenameArgument
          properties:
            "@id": "<_>"
            "@type": <fdri:ConfigurationArgument>
            "<fdri:parameter>": <http://fdri.ceh.ac.uk/ref/common/parameter/mask_filename>
            "<fdri:hasValue>":
              - name: MaskFilenameArgumentValue
                properties:
                  "@id": <_>
                  "@type": <schema:PropertyValue>
                  "<schema:value>": "{MASK_FILENAME}"
  - name: HistoricalConfigurationItem
    requires:
      END:
    properties:
      "@id": "<http://fdri.ceh.ac.uk/id/configuration-item/{SITE_ID|slug}-{FEATURE_ID|slug}-{RESOLUTION|slug}-{SEQ|slug}>"
      "@type": <fdri:ConfigurationItem>
      "^<fdri:hadConfiguration>": <::MaskConfiguration>
      "<fdri:observationInterval>":
        - name: ClosedDateRange
          properties:
            "@id": "<_>"
            "@type": <dct:PeriodOfTime>
            "<dcat:startDate>": "{START}^^<xsd:dateTime>"
            "<dcat:endDate>": "{END}^^<xsd:dateTime>"
  - name: CurrentConfigurationItem
    requires:
      END: ''
    properties:
      "@id": "<http://fdri.ceh.ac.uk/id/configuration-item/{SITE_ID|slug}-{FEATURE_ID|slug}-{RESOLUTION|slug}-{SEQ|slug}>"
      "@type": <fdri:ConfigurationItem>
      "^<fdri:hasCurrentConfiguration>": <::MaskConfiguration>
      "<fdri:observationInterval>":
        - name: OpenDateRange
          properties:
            "@id": "<_>"
            "@type": <dct:PeriodOfTime>
            "<dcat:startDate>": "{START}^^<xsd:dateTime>"
