globals:
  $baseURI: http://fdri.ceh.ac.uk/
  $datasetID: cosmos

imports:
  - namespaces.yaml
  - concept_schemes.yaml
  - extensions.py

resources:
  - name: FlagTS
    properties:
      "@id": "<http://fdri.ceh.ac.uk/id/dataset/{FLAG_TS|slug}>"
  - name: Method
    properties:
      "@id": "<http://fdri.ceh.ac.uk/ref/common/method/{METHOD_ID|slug}>"
  - name: Parameter
    properties:
      "@id": "<http://fdri.ceh.ac.uk/ref/common/parameter/{PARAM_ID|slug}>"    
  - name: ProcessingConfiguration
    properties:
      "@id": "<http://fdri.ceh.ac.uk/id/data-processing-configuration/{FLAG_TS|slug}-{METHOD_ID|slug}>"
      "@type": <fdri:InternalDataProcessingConfiguration>
      "<dct:type>": "<http://fdri.ceh.ac.uk/ref/common/configuration-type/qc>"
      "<fdri:appliesToTimeSeries>": <::FlagTS>
  - name: CurrentConfigurationItem
    properties:
      "@id": "<http://fdri.ceh.ac.uk/id/configuration-item/{FLAG_TS|slug}-{METHOD_ID|slug}-current>"
      "@type": <fdri:ConfigurationItem>
      "^<fdri:hasCurrentConfiguration>": <::ProcessingConfiguration>
  - name: ConfigurationArgument
    properties:
      "@id": "<http://fdri.ceh.ac.uk/id/configuration-argument/{FLAG_TS|slug}-{METHOD_ID|slug}-{PARAM_ID|slug}-current>"
      "@type": <fdri:ConfigurationArgument>
      "<fdri:parameter>": <::Parameter>
      "^<fdri:argument>": <::CurrentConfigurationItem>

  - name: NumericValue
    requires:
      PARAM_NUMERIC_VALUE:
    properties:
      "@id": "<http://fdri.ceh.ac.uk/configuration-argument/{FLAG_TS|slug}-{METHOD_ID|slug}-{PARAM_ID|slug}-current#value>"
      "@type": <schema:PropertyValue>
      "<schema:value>": "{PARAM_NUMERIC_VALUE}@<xsd:integer>"
      "^<fdri:hasValue>": <::ConfigurationArgument>
  - name: TSRefValue
    requires:
      PARAM_TS_VALUE:
    properties:
      "@id": "<http://fdri.ceh.ac.uk/configuration-argument/{FLAG_TS|slug}-{METHOD_ID|slug}-{PARAM_ID|slug}-current#value>"
      "@type": <schema:PropertyValue>
      "<schema:valueReference>": "<http://fdri.ceh.ac.uk/id/dataset/{PARAM_TS_VALUE|slug}>"
      "^<fdri:hasValue>": <::ConfigurationArgument>
