globals:
  $baseURI: http://fdri.ceh.ac.uk/
  $datasetID: cosmos

imports:
  - namespaces.yaml
  - concept_schemes.yaml
  - extensions.py

one_offs:
  - name: RangeCheck
    properties:
      "@id": "<http://fdri.ceh.ac.uk/ref/common/configuration-type/qc-range>"
      "@type": "<fdri:DataProcessingConfigurationType>"
      "<skos:prefLabel>": "Range Validation@en"
      "<rdfs:label>": "Range Validation@en"
      "<skos:inScheme>": "<::ConfigurationTypeScheme>"
      "^<skos:hasTopConcept>": "<::ConfigurationTypeScheme>"

  - name: Range
    properties:
      "@id": "<http://fdri.ceh.ac.uk/ref/common/parameter/range>"
      "@type": "<fdri:ConfigurationParameter>"
      "<skos:prefLabel>": "Expected Range@en"
      "<rdfs:label>": "Expected Range@en"
      "<skos:inScheme>": "<::ConfigurationParameterScheme>"
      "^<skos:hasTopConcept>": "<::ConfigurationParameterScheme>"

  - name: MinMaxRange
    properties:
      "@id": "<http://fdri.ceh.ac.uk/ref/common/method/min-max-range>"
      "@type": "<fdri:DataProcessingMethod>"
      "<skos:prefLabel>": "Min/Max range validation@en"
      "<rdfs:label>": "Min/Max range validation@en"
      "<skos:inScheme>": "<::DataProcessingMethodScheme>"
      "^<skos:hasTopConcept>": "<::DataProcessingMethodScheme>"

resources:
  - name: Configuration
    properties:
      "@id": "<http://fdri.ceh.ac.uk/id/data-processing-configuration/cosmos-qc-range-{SITE_ID|slug}-{TIMESERIES_ID|slug}>"
      "@type": "<fdri:InternalDataProcessingConfiguration>"
      "<fdri:appliesToFacility>": <http://fdri.ceh.ac.uk/id/site/cosmos-{SITE_ID|slug}>
      "<fdri:appliesToTimeSeries>": <http://fdri.ceh.ac.uk/ref/cosmos/time-series/{TIMESERIES_ID|slug}>
      "<dct:type>": <::RangeCheck>

  - name: ConfigurationItem
    properties:
      "@id": "<http://fdri.ceh.ac.uk/id/configuration-item/cosmos-qc-range-{SITE_ID|slug}-{TIMESERIES_ID|slug}>"
      "@type": "<fdri:ConfigurationItem>"
      "<fdri:method>": "<::MinMaxRange>"
      "<fdri:argument>":
        name: ConfigurationArg
        properties:
          "@id": "<_>"
          "@type": "<fdri:ConfigurationArgument>"
          "<fdri:parameter>": "<::Range>"
          "<fdri:hasValue>":
            name: ConfigurationValue
            properties:
              "@id": "<_>"
              "@type": "<schema:PropertyValue>"
              "<schema:minValue>": "{MINVAL|asDecimal}"
              "<schema:maxValue>": "{MAXVAL|asDecimal}"
      "<fdri:interval>":
        name: Interval
        properties:
          "@id": "<_>"
          "@type": "<dct:PeriodOfTime>"
          "<dcat:startDate>": "{| now}"
      "^<fdri:hasCurrentConfiguration>": "<http://fdri.ceh.ac.uk/id/data-processing-configuration/cosmos-qc-range-{SITE_ID|slug}-{TIMESERIES_ID|slug}>"
      "^<prov:hadPlan>": "<http://fdri.ceh.ac.uk/id/activity/qc-cosmos-{SITE_ID|slug}-{TIMESERIES_ID|slug}-1234>"
