globals:
    $baseURI: http://fdri.ceh.ac.uk/
    $datasetID: default

imports:
    - namespaces.yaml
    - extensions.py

resources:

  - name: Feature
    properties:
      "@id": "<http://fdri.ceh.ac.uk/id/feature/cosmos-{SITE_ID|slug}>"
      "@type": <fdri:GeospatialFeatureOfInterest>

  - name: Sensor
    requires:
      INSTRUMENT_ID:
      SERIAL_NUMBER:
    properties:
      "@id": "<http://fdri.ceh.ac.uk/id/sensor/cosmos-{INSTRUMENT_ID|slug}-{SERIAL_NUMBER|slug}>"
      "@type": "<fdri:EnvironmentalMonitoringSensor>"
      "<rdfs:label>": "{INSTRUMENT_ID} {SERIAL_NUMBER}@en"
      "<dct:type>": "<http://fdri.ceh.ac.uk/ref/cosmos/monitoring-system-type/{INSTRUMENT_ID|slug}>"
      "<fdri:serialNumber>": "{SERIAL_NUMBER}"

  - name: SensorSlot
    requires:
      SENSOR_SLOT_ID:
    properties:
      "@id": "<http://fdri.ceh.ac.uk/id/platform/cosmos-{SITE_ID|slug}-{SENSOR_SLOT_ID|slug}>"
      "@type": "<fdri:EnvironmentalMonitoringPlatform>"
      "<rdfs:label>": "{SENSOR_SLOT_NAME} at {SITE_ID}@en"
      "<fdri:hasAnnotation>": "<::SensorSlotNameAnnotation>"
      "^<dct:hasPart>": "<http://fdri.ceh.ac.uk/id/site/cosmos-{SITE_ID|slug}>"

  - name: SensorSlotNameAnnotation
    requires:
      SENSOR_SLOT_NAME:
    properties:
      "@id": "<http://fdri.ceh.ac.uk/id/platform/cosmos-{SITE_ID|slug}-{SENSOR_SLOT_ID|slug}#sensor-slot-name>"
      "@type": <fdri:Annotation>
      "<fdri:property>": "<http://fdri.ceh.ac.uk/ref/common/annotation-property/sensor_slot_name>"
      "<fdri:hasValue>":
        - name: SensorSlotName
          properties:
            "@id": "<http://fdri.ceh.ac.uk/id/platform/cosmos-{SITE_ID|slug}-{SENSOR_SLOT_ID|slug}#sensor-slot-name.value>"
            "@type": <schema:PropertyValue>
            "<schema:value>": "{SENSOR_SLOT_NAME}"

  - name: SensorDeployment
    requires:
      INSTRUMENT_ID:
      SERIAL_NUMBER:
    properties:
      "@id": "<http://fdri.ceh.ac.uk/id/deployment/cosmos-{SITE_ID|slug}-{SENSOR_SLOT_ID|slug}-{INSTRUMENT_ID|slug}-{SERIAL_NUMBER|slug}-{INSTANCE|asInt}>"
      "@type": "<fdri:StaticDeployment>"
      "<rdfs:label>": "Deployment of {INSTRUMENT_ID} {SERIAL_NUMBER} to {SENSOR_SLOT_ID} at {SITE_ID}@en"
      "<ssn:deployedSystem>": "<::Sensor>"
      "<ssn:deployedOnPlatform>": "<::SensorSlot>"
      "<prov:startedAtTime>": "{START_DATETIME|asDateTime}"
      "<fdri:deployedHeight>": "{INSTALLATION_HEIGHT|asDecimal}"

  - name: SensorDeploymentEnd
    requires:
      INSTRUMENT_ID:
      SERIAL_NUMBER:
      END_DATETIME:
    properties:
      "@id": "<http://fdri.ceh.ac.uk/id/deployment/cosmos-{SITE_ID|slug}-{SENSOR_SLOT_ID|slug}-{INSTRUMENT_ID|slug}-{SERIAL_NUMBER|slug}-{INSTANCE|asInt}>"
      "<prov:endedAtTime>": "{END_DATETIME|asDateTime}"

  - name: SensorDeploymentComments
    requires:
      INSTRUMENT_ID:
      SERIAL_NUMBER:
      COMMENTS:
    properties:
      "@id": "<http://fdri.ceh.ac.uk/id/deployment/cosmos-deployment-{SITE_ID|slug}-{INSTRUMENT_ID|slug}-{SERIAL_NUMBER|slug}-{INSTANCE|asInt}>"
      "<rdfs:comment>": "{COMMENTS}@en"
