globals:
    $baseURI: http://fdri.ceh.ac.uk/
    $datasetID: cosmos

imports:
    - namespaces.yaml
    - extensions.py

resources:

  - name: Feature
    properties:
      "@id": "<http://fdri.ceh.ac.uk/id/feature/cosmos-{SITE_ID|slug}>"
      "@type": <fdri:GeospatialFeatureOfInterest>

  - name: Sensor
    requires:
      SERIAL_NUMBER:
    properties:
      "@id": "<http://fdri.ceh.ac.uk/id/sensor/cosmos-{INSTRUMENT_ID|slug}-{SERIAL_NUMBER|slug}>"
      "@type": "<fdri:EnvironmentalMonitoringSensor>"
      "<dct:title>": "{INSTRUMENT_ID} {SERIAL_NUMBER}@en"
      "<dct:type>": "<http://fdri.ceh.ac.uk/ref/cosmos/monitoring-system-type/{INSTRUMENT_ID|slug}>"
      "<fdri:serialNumber>": "{SERIAL_NUMBER}"

  - name: SensorDeployment
    requires:
      SERIAL_NUMBER:
    properties:
      "@id": "<http://fdri.ceh.ac.uk/id/activity/cosmos-deployment-{SITE_ID|slug}-{INSTRUMENT_ID|slug}-{SERIAL_NUMBER|slug}-{INSTANCE|asInt}>"
      "@type": "<fdri:Deployment>"
      "<dct:title>": "Deployment of {INSTRUMENT_ID} {SERIAL_NUMBER} at {SITE_ID}@en"
      "<ssn:deployedSystem>": "<http://fdri.ceh.ac.uk/id/sensor/cosmos-{INSTRUMENT_ID|slug}-{SERIAL_NUMBER|slug}>"
      "<ssn:deployedOnPlatform>": "<http://fdri.ceh.ac.uk/id/site/cosmos-{SITE_ID|slug}>"
      "<prov:startedAtTime>": "{START_DATETIME|asDateTime}"
  - name: SensorDeploymentEnd
    requires:
      SERIAL_NUMBER:
      END_DATETIME:
    properties:
      "@id": "<http://fdri.ceh.ac.uk/id/activity/cosmos-deployment-{SITE_ID|slug}-{INSTRUMENT_ID|slug}-{SERIAL_NUMBER|slug}-{INSTANCE|asInt}>"
      "@type": "<fdri:Deployment>"
      "<prov:endedAtTime>": "{END_DATETIME|asDateTime}"
  - name: SensorDeploymentComments
    requires:
      SERIAL_NUMBER:
      COMMENTS:
    properties:
      "@id": "<http://fdri.ceh.ac.uk/id/activity/cosmos-deployment-{SITE_ID|slug}-{INSTRUMENT_ID|slug}-{SERIAL_NUMBER|slug}-{INSTANCE|asInt}>"
      "@type": "<fdri:Deployment>"
      "<dct:description>": "{COMMENTS}@en"
