name: publish sample data
on:
  workflow_dispatch: {}
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write
  actions: read
    
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo 
        uses: actions/checkout@v4
      - name: Git fetch
        run: |
          git fetch --prune --unshallow --tags

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Test pulling docker image
        run: |
          docker pull 293385631482.dkr.ecr.eu-west-1.amazonaws.com/epimorphics/record-spec-tools/unstable:1.0-SNAPSHOT

      - name: Build sample data
        run: make samples

      - name: Publish sample data
        run: bash publish.sh
