name: publish sample data
on:
  workflow_dispatch: {}
  push:
    branches:
      - production
      - staging

permissions:
  contents: write
  pages: write
  id-token: write
  actions: read
  pull-requests: write
    
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Git fetch
        run: |
          git fetch --prune --unshallow --tags

      - name: Checkout rdf-mapper
        uses: actions/checkout@v4
        with:
          repository: NERC-CEH/dri-gridded-mapper
          path: gridded-mapper
      
      - name: Install netCDF tools
        run: |
          sudo apt-get update
          sudo apt-get install -y netcdf-bin

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install gridded-mapper
        working-directory: gridded-mapper
        run: |
          pip install .

      - name: Configure AWS Credentials for Epimorphics
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.BUILD_CEH_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.BUILD_CEH_AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Test pulling docker image
        run: |
          docker pull 293385631482.dkr.ecr.eu-west-1.amazonaws.com/epimorphics/record-spec-tools/unstable:1.0-SNAPSHOT

      - name: Build sample data
        run: make samples

      - name: Configure AWS Credentials for UKCEH Staging
        if: ${{ github.ref == 'refs/heads/staging' }}
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN_STAGING }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Configure AWS Credentials for UKCEH Prod
        if: ${{ github.ref == 'refs/heads/production' }}
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN_PROD }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Publish sample data to new account
        run: bash publish.sh

  create-staging-to-production-pr:
    needs: [publish]
    if: ${{ needs.publish.result == 'success' && github.ref_name == 'staging' }}
    uses: NERC-CEH/dri-cicd/.github/workflows/auto-create-pr.yml@main
    with:
      base: production
      head: staging

