name: test sample data generation
on:
  pull_request:
  workflow_dispatch: 

permissions:
  contents: read
  pages: write
  id-token: write
  actions: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo 
        uses: actions/checkout@v4
      - name: Git fetch
        run: |
          git fetch --prune --unshallow --tags

      - name: Configure AWS Credentials for Epimorphics
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.BUILD_CEH_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.BUILD_CEH_AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Pull worker image
        run: |
          docker pull 293385631482.dkr.ecr.eu-west-1.amazonaws.com/epimorphics/record-spec-tools/unstable:1.0-SNAPSHOT

      - name: Build sample data
        run: make samples

      - name: Upload validation results
        uses: actions/upload-artifact@v4
        with:
          name: shacl-validation
          path: build/validation/*.ttl
          overwrite: true